name: Plugin asset/readme update
on:
  push:
    branches:
    - main
jobs:
  asset-readme-update:
    name: Update WordPress.org assets
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: WordPress.org plugin asset/readme update
      uses: 10up/action-wordpress-plugin-asset-update@475933817c3b9b6cc65a4fe3dad69b98e8b11c5f
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
